version: 0.1

environment_variables:
  plaintext:
    HUGO_VERSION: "0.56.3"
    HUGO_SHA256: "1bd70ef3fab865262a9111b90c4ddc0e7325370296f9b49be96c85a7117f463e"

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y git python-pip
      - pip install Pygments
      - curl -Ls https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb -o /tmp/hugo.deb
      - echo "${HUGO_SHA256}  /tmp/hugo.deb" | sha256sum -c -
      - dpkg -i /tmp/hugo.deb
#      - (cd themes; git clone https://github.com/wolfeidau/hugo-type-theme type)
  build:
    commands:
      - hugo
  post_build:
    commands:
      - aws s3 sync --delete public s3://${BUCKET_NAME} --cache-control max-age=3600 --acl public-read