version: 0.1

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "us-west-2"
    HUGO_VERSION: "0.21"
    HUGO_SHA256: "846cb229c092d6187fcd49a7fc23c1ee416a2525bb99761ba02f6eecc0ab0825"

phases:
  install:
    commands:
      - curl -Ls https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb -o /tmp/hugo.deb
      - echo "${HUGO_SHA256}  /tmp/hugo.deb" | sha256sum -c -
      - dpkg -i /tmp/hugo.deb
  build:
    commands:
      - hugo
  post_build:
    commands:
      - aws s3 sync --delete public s3://${BUCKET_NAME} --cache-control max-age=3600