version: 0.1

environment_variables:
  plaintext:
    HUGO_VERSION: "0.56.3"
    HUGO_SHA256: "c062d7cb73945c70cde00f3f858fe2640a82c248dae328f2536dab36d5f6e896"

phases:
  install:
    commands:
      - apt-get update
      - curl -Ls https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb -o /tmp/hugo.deb
      - echo "${HUGO_SHA256}  /tmp/hugo.deb" | sha256sum -c -
      - dpkg -i /tmp/hugo.deb
      - (cd themes; git clone https://github.com/digitalcraftsman/hugo-type-theme hugo-type-theme)
  build:
    commands:
      - hugo
  post_build:
    commands:
      - aws s3 sync --delete public s3://${BUCKET_NAME} --cache-control max-age=3600 --acl public-read