baseurl = "https://www.wolfe.id.au/"
languageCode = "en-us"
title = "Mark Wolfe's Blog"

disqusShortname = "markwolfesblog"
googleAnalytics = "UA-10420512-2"
theme = "type"

paginate = 10

[permalinks]
    post = "/:year/:month/:day/:title/"

[social]
    twitter = "wolfeidau"

[Authors.wolfeidau]
    given_name   = "Mark"
    family_name  = "Wolfe"
    display_name = "Mark Wolfe"
    twitter = "wolfeidau"

[params]
    author = "Mark Wolfe"
    description = "A place to post ideas"
    avatar = "images/wolfeidau.jpeg"
    copyright = "Released under the MIT license<br>Powered by [Hugo](//gohugo.io/)"

    [params.social]
        rss = true
        email = "mark@wolfe.id.au"
        github = "wolfeidau"
        twitter = "wolfeidau"
