baseurl = "https://dh3njxxxcp7z0.cloudfront.net/"
languageCode = "en-us"
title = "Mark Wolfe's Blog"

disqusShortname = "markwolfesblog"
googleAnalytics = "UA-10420512-2"
theme = "type"

uglyurls = true

paginate = 10

[params]
    author = "Mark Wolfe"
    description = "A place to post ideas"
    avatar = "images/wolfeidau.jpeg"
    copyright = "Released under the MIT license<br>Powered by [Hugo](//gohugo.io/)"

    [params.social]
        rss = true
        email = "mark@wolfe.id.au"
        github = "wolfeidau"
        twitter = "wolfeidau"
