name: 'Push'

# The workflow should only trigger on push events to the main branch
on:
  push:
    branches:
      - master

# Required to get the ID Token that will be used for OIDC
permissions:
  id-token: write

jobs:

  deploy-prod:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          aws-region: ${{ secrets.PROD_DEPLOY_REGION }}
          role-to-assume: ${{ secrets.PROD_DEPLOY_ROLE }}
          role-session-name: OIDCSession
      
      - name: build
        env:
          HUGO_ENVIRONMENT: production
          HUGO_PARAMS_POSTHOG_TOKEN: ${{ secrets.POSTHOG_TOKEN }}
          HUGO_PARAMS_POSTHOG_APIHOST: ${{ secrets.POSTHOG_API_HOST }}
        run: make docker-build
      
      - name: upload
        env:
          STAGE: prod
        run: make upload
